# Project-1 (Sales panel of a regional distribution company)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Exploration

In [2]:
df = pd.read_csv('ecommerce_sales_data.csv')

df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [3]:
df.shape

(3500, 7)

In [4]:
df.dtypes

Order Date       object
Product Name     object
Category         object
Region           object
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 191.5+ KB

In [6]:
df.columns

Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='object')

In [7]:
df.isnull().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

In [8]:
df.describe()

          Quantity         Sales       Profit
count  3500.000000   3500.000000  3500.000000
mean      4.931714   3047.966000   527.047203
std       2.575895   2440.213237   504.139732
min       1.000000     51.000000     6.970000
25%       3.000000   1049.500000   158.695000
50%       5.000000   2350.500000   361.070000
75%       7.000000   4537.000000   729.125000
max       9.000000  10782.000000  2946.930000

In [9]:
df.describe(include = 'object')

        Order Date Product Name     Category Region
count         3500         3500         3500   3500
unique        1051           10            3      4
top     2023-08-12      Monitor  Electronics   West
freq            11          364         1742    898

In [10]:
df['Category'].unique()

array(['Office', 'Accessories', 'Electronics'], dtype=object)

In [11]:
df['Category'].value_counts()

Category
Electronics    1742
Accessories    1401
Office          357
Name: count, dtype: int64

In [12]:
df['Product Name'].value_counts()

Product Name
Monitor       364
Camera        363
Smartwatch    363
Printer       357
Keyboard      351
Tablet        350
Mouse         347
Headphones    339
Laptop        336
Smartphone    330
Name: count, dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

# Cleaning

In [14]:
df.columns = df.columns.str.strip().str.replace(" ","_")

In [15]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [16]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Month_Name'] = df['Order_Date'].dt.month_name()
df['Quarter'] = df['Order_Date'].dt.quarter

In [17]:
df['Unit_Price'] = df['Sales'] / df['Quantity']

In [18]:
df = df.sort_values(by='Order_Date')

In [19]:
df.reset_index(drop=True, inplace=True)

In [20]:
df.head()

,Order_Date,Product_Name,Category,Region,Quantity,Sales,Profit,Year,Month,Month_Name,Quarter,Unit_Price
0,2022-01-01,Mouse,Accessories,East,3,3474,565.00,2022,1,January,1,1158.0
1,2022-01-01,Monitor,Accessories,South,8,1296,273.97,2022,1,January,1,162.0
2,2022-01-01,Tablet,Electronics,North,9,9234,2523.67,2022,1,January,1,1026.0
3,2022-01-01,Headphones,Accessories,South,7,3941,628.96,2022,1,January,1,563.0
4,2022-01-01,Keyboard,Accessories,East,6,6372,570.75,2022,1,January,1,1062.0

In [21]:
df.to_csv('clean_ecommerce_sales.CSV', index=False)